x

diff --git a/provision b/provision
--- a/provision
+++ b/provision
@@ -4,10 +4,18 @@ SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 DOCKER_DIR="$SCRIPT_DIR/docker"
 
 PUPPET_DIR="${PUPPET_SOURCE:-$SCRIPT_DIR/puppet}"
-DOCKER_OS="${DOCKER_OS:-centos}"
+DOCKER_OS="${DOCKER_OS:-ubuntu}"
 DOCKER_OS="$(echo ${DOCKER_OS} | tr '[:upper:]' '[:lower:]')"
 DOCKER_PUPPET_IMAGE="${DOCKER_PUPPET_IMAGE:-puppet-testbase-${DOCKER_OS}}"
 DOCKER_PID="${DOCKER_DIR}/docker-${DOCKER_OS}.pid"
+
+
+if [[  $# == 0  ]]; then
+	echo Missing hostname
+	exit 1
+fi
+HOSTNAME=$1
+
 
 # Support setting a special puppet dir. This is mainly to support running in Vagrant.
 if [[ -e /puppet ]]; then
@@ -58,7 +66,7 @@ if [[ ! $DOCKER_PATH ]]; then
 fi
 
 # Work around for security constraint in docker. Will be fixed later with groups.
-sudo chmod 777 /var/run/docker.sock
+# sudo chmod 777 /var/run/docker.sock
 
 echo " "
 if [[ ! "$(puppetImage)" ]]; then
@@ -74,11 +82,51 @@ if [[ ! "$(puppetImage)" ]]; then
 fi
 
 if [[ ! "$(puppetImage)" ]]; then
-	echo "Building the puppet image has failed! Aborting."	
+	echo "Building the puppet image has failed! Aborting."
 	exit 1
 fi
 
-DOCKER_PS=$(cat $DOCKER_PID || true;)
+function getIP() {
+	docker inspect --format '{{ .NetworkSettings.IPAddress }}' "$HOSTNAME" 2> /dev/null
+}
+
+# IPADRESS=$(getIP)
+# echo --$(getIP)--
+
+
+
+# exit 1
+if [[ "$(getIP)" == "" ]]; then
+	echo "poustim"
+	DOCKER_PS=$(docker run -d -h "$HOSTNAME" --label "locloud" --name "$HOSTNAME" -p 22 -t -v $PUPPET_DIR:/puppet -v $DOCKER_DIR:/docker $DOCKER_PUPPET_IMAGE /usr/sbin/sshd -D)
+
+	# ssh  -i ssh_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$IPADDRESS -p 22 "/docker/run_puppet.sh"
+	#TODO chytrejs
+	sleep 1
+fi
+
+
+IP=$(getIP)
+echo "Provision $IP"
+#
+ssh  -i ssh_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$IP -p 22 "/docker/run_puppet.sh"
+
+echo bezi
+
+	# echo "poustim"
+	# DOCKER_PS=$(docker run -d -h "$HOSTNAME" --name "$HOSTNAME" -p 22 -t -v $PUPPET_DIR:/puppet -v $DOCKER_DIR:/docker $DOCKER_PUPPET_IMAGE /usr/sbin/sshd -D)
+	# dockerR
+# fi
+
+docker ps
+
+# DOCKER_PS=$(docker run -d -h "$HOSTNAME" --name "$HOSTNAME" -p 22 -t -v $PUPPET_DIR:/puppet -v $DOCKER_DIR:/docker $DOCKER_PUPPET_IMAGE /usr/sbin/sshd -D)
+
+# echo $DOCKER_PS
+
+# DOCKER_PS=$(cat $DOCKER_PID || true;)
+# echo DOCKER_PS
+exit 1
 # If already created and still running. Stop the container to create a new one.
 if [[ "$(dockerRunning "$DOCKER_PS")" ]]; then
 	echo " "
@@ -98,9 +146,8 @@ echo "Running puppet"
 echo " "
 # Sleeping to let everything start up. Nasty...
 sleep 1s
-echo $DOCKER_PS
 SSH_PORT=$(docker port $DOCKER_PS 22 | cut -f2 -d ':')
-ssh -q -i ssh_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@localhost -p $SSH_PORT "/docker/run_puppet.sh"
+ssh  -i ssh_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@192.168.59.103 -p $SSH_PORT "/docker/run_puppet.sh"
 
 echo " "
 echo " Done ! $(date)"
